name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test_groovy:
    name: Groovy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Run Groovy Tests
      run: |
        cd adopt-github-release
        ./gradlew --info test